config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount MissionControl::Jobs::Engine, at: "/jobs"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#home"

  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout' }, only: [:sessions]

  resources :imports, only: [:new, :create] do
    collection do
      post :categories
    end
  end
  
  namespace :api do
    namespace :v1 do
      resources :entreprises, only: [:index]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entreprise.rb
class Entreprise < ApplicationRecord
end

app/models/import_file.rb
class ImportFile < ApplicationRecord
    has_one_attached :file
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/entreprises_controller.rb
class Api::V1::EntreprisesController < ApplicationController
  def index
    codes = [14, 46, 47, 56]

    entreprises = Entreprise
      .where("CHAR_LENGTH(isic_2_dig::text) = ?", 2)
      .where.not(latitude: nil, longitude: nil)
      .where(isic_2_dig: codes)

    categories = Entreprise
      .select("isic_2_dig, isic_2_dig_description")
      .where("CHAR_LENGTH(isic_2_dig::text) = ?", 2)
      .where.not(latitude: nil, longitude: nil)
      .where(isic_2_dig: codes)
      .group("isic_2_dig, isic_2_dig_description")
      
    colors = generate_category_colors(categories)

    render json: {
      entreprises: entreprises,
      categories: categories,
      colors: colors
    }
  end

  private

  def generate_category_colors(categories)
    predefined_colors = {}
    color_names = %w[red blue green yellow orange purple pink brown black white]
    count = categories.length

    extended_color_names = generate_extended_colors(color_names, count)

    categories.each_with_index do |category, index|
      predefined_colors[category.isic_2_dig_description] = extended_color_names[index]
    end

    predefined_colors
  end

  def generate_extended_colors(color_names, count)
    extended_colors = color_names.dup
    extended_colors += color_names while extended_colors.size < count
    extended_colors.take(count)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/imports_controller.rb
# app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_action :authenticate_user!

  def new
    @import_file = ImportFile.new
  end

  def create
    @import_file = ImportFile.new
    handle_file_upload(@import_file, ImportEntrepriseDataJob)
  end

  private

  def handle_file_upload(import_file, job)
    import_file.file.attach(import_params[:file])
    import_file.status = 'pending'

    if import_file.save
      job.perform_later(import_file.id)
      redirect_to root_path, notice: 'File uploaded. Processing in the background.'
    else
      render :new
    end
  end

  def import_params
    params.require(:import_file).permit(:file)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/imports/create.html.erb
<h1>Imports#create</h1>
<p>Find me in app/views/imports/create.html.erb</p>

app/views/imports/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header mb-2">
          Importer les entreprises
        </div>
        <div class="card-body">
          <%= form_with(model: ImportFile.new, url: imports_path, local: true, html: { multipart: true }) do |form| %>
            <div class="form-group">
              <%= form.file_field :file, class: 'form-control' %>
            </div>
            <%= form.submit 'Upload', class: 'btn btn-primary my-3' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Carte interactive des entreprises africaines" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <%= link_to root_path, class: 'navbar-brand px-2' do %>
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Georeferenced_observation.png/828px-Georeferenced_observation.png?20231130123035" width="40" height="40" alt="Weebi">
          <% end %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "Import", new_import_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Jobs", mission_control_jobs_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Admin", rails_admin_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "DB", rails_db_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to current_user.email, root_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "nav-link text-danger" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="container">
      <div class="col-md-6 mx-auto">
        <% if notice %>
          <div class="alert alert-primary alert-dismissible fade show py-2" role="alert">
            <%= notice %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
        <% if alert %>
          <div class="alert alert-warning alert-dismissible fade show py-2" role="alert">
            <%= alert %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
      </div>
    </div>

    <div class="main-hero">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<%# <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/0.4.2/leaflet.draw.css"/> %>

<div data-controller="map">
  <div data-map-target="mapContainer" style="width: 100%; height: 90vh;"></div>
</div>